import type { Pack } from './types.ts';

// the reference packs. a repo overrides any of them with .sift/packs/<name>.json in the same shape
export const BUILTIN_PACKS: Record<string, Pack> = {
  issue: {
    name: 'issue',
    subject: 'issue',
    description: 'Is this issue well formed, correctly typed, scoped to this repo, and ready to work on?',
    checks: ['issue.labels', 'issue.milestone', 'issue.template', 'issue.parent'],
    questions: {
      substantive: {
        type: 'noul',
        instructions: 'The body describes a concrete problem or change with enough detail that someone could start work without asking what is meant.',
        criteria: 'A body of placeholder text, a bare title restated, or a single sentence with no context does not satisfy this.',
        severity: 'warn',
      },
      type: {
        type: 'choice',
        instructions: 'Which kind of issue is this, judged from the title and body alone?',
        options: 'type_labels',
        severity: 'info',
      },
      single_repo: {
        type: 'noul',
        instructions: 'The requested change can be completed entirely within this repository.',
        criteria: 'An issue that requires a change in another named repository or an upstream dependency first does not satisfy this.',
        severity: 'warn',
      },
      needs_parent: {
        type: 'noul',
        instructions: 'This issue reads as one part of a larger effort that should be tracked by a parent issue.',
        severity: 'info',
      },
      duplicate_of: {
        type: 'choice',
        instructions: 'Which open issue, if any, asks for the same change as this one?',
        options: 'open_issues',
        when: 'has_others',
        severity: 'warn',
        hi: 0.7,
      },
      readiness: {
        type: 'score',
        instructions: 'How ready is this issue to be worked on?',
        criteria: [
          'needs author input: the request cannot be understood or has contradictory requirements',
          'needs triage: understandable but missing scope, acceptance criteria, or a decision',
          'ready: clear enough to start implementing now',
        ],
        severity: 'info',
      },
    },
  },
  pr: {
    name: 'pr',
    subject: 'pr',
    description: 'Does this PR do what its issue asks, nothing more, without workarounds, and is it safe to merge?',
    checks: ['pr.linked', 'pr.target', 'pr.branch', 'pr.ci', 'pr.template', 'pr.commits'],
    questions: {
      addresses_issue: {
        type: 'noul',
        instructions: 'The diff implements what the linked issue asks for.',
        criteria: 'A diff that solves a different problem, or only part of the issue with no explanation, does not satisfy this.',
        when: 'has_issue',
        severity: 'fail',
      },
      scope_creep: {
        type: 'noul',
        instructions: 'The diff changes files or behaviour unrelated to the stated purpose of the PR.',
        criteria: 'Unrelated refactors, formatting sweeps, or drive-by fixes in other subsystems count. A small change required to make the main change compile does not.',
        inverted: true,
        severity: 'warn',
      },
      workaround: {
        type: 'noul',
        instructions: 'The diff patches a symptom rather than its cause: a defensive fallback, a swallowed error, a special case added where a general fix was needed, or a TODO left in place of the fix.',
        inverted: true,
        severity: 'warn',
      },
      contract_change: {
        type: 'noul',
        instructions: 'The diff changes a public interface, file format, CLI surface, or protocol that code outside this repository could depend on.',
        inverted: true,
        severity: 'info',
      },
      tests_cover: {
        type: 'noul',
        instructions: 'The behaviour the diff adds or changes is exercised by tests in the same diff or by existing tests it visibly updates.',
        when: 'has_diff',
        severity: 'info',
      },
      risk: {
        type: 'score',
        instructions: 'How likely is this PR to break something that works today?',
        criteria: [
          'low: additive or isolated, easy to revert',
          'medium: touches shared code paths or state',
          'high: changes core logic, data formats, or concurrency, or is very large',
        ],
        severity: 'info',
      },
    },
  },
  commit: {
    name: 'commit',
    subject: 'commit',
    description: 'Do these commit messages follow the convention and describe their diffs honestly?',
    checks: ['commit.format'],
    questions: {
      type_matches: {
        type: 'choice',
        instructions: 'Which conventional commit type does the diff actually warrant?',
        options: 'commit_types',
        when: 'has_diff',
        severity: 'info',
      },
      describes_change: {
        type: 'noul',
        instructions: 'The commit subject line accurately describes what the diff does.',
        criteria: 'A subject that names a different change, is vague (update, fix stuff, wip), or claims more than the diff does, does not satisfy this.',
        when: 'has_diff',
        severity: 'warn',
      },
      breaking_missed: {
        type: 'noul',
        instructions: 'The diff removes or changes a public interface in a way that breaks existing callers, yet the message does not mark it as breaking.',
        when: 'has_diff',
        inverted: true,
        severity: 'fail',
      },
    },
  },
  release: {
    name: 'release',
    subject: 'release',
    description: 'What semver bump do the commits since the last tag require, and does the changelog match?',
    checks: ['release.commits', 'release.bump', 'release.changelog'],
    questions: {
      hidden_breaking: {
        type: 'noul',
        instructions: 'At least one commit since the last tag describes a change that breaks existing users but is not marked as breaking.',
        when: 'has_commits',
        inverted: true,
        severity: 'fail',
      },
      changelog_complete: {
        type: 'noul',
        instructions: 'The top changelog section mentions every user-visible change among the commits.',
        when: 'has_commits',
        severity: 'warn',
      },
    },
  },
  rules: {
    name: 'rules',
    subject: 'rules',
    description: 'Does the subject comply with each rule stated in the repository rule documents?',
    checks: ['rules.present'],
    questions: {},
    expand: {
      from: 'rules',
      template: {
        type: 'noul',
        instructions: 'The subject complies with this rule: {text}',
        criteria: 'Answer near 0.5 when the rule does not apply to this subject at all.',
        severity: 'warn',
        lo: 0.3,
        hi: 0.6,
      },
    },
  },
  triage: {
    name: 'triage',
    subject: 'event',
    description: 'Does this repository event need the session to act on it now?',
    checks: [],
    questions: {
      actionable: {
        type: 'noul',
        instructions: 'This event needs the repository maintainer to do something now: reply, triage, fix, review, or merge.',
        criteria: 'Label churn, a bot status update, a thank-you comment, or a duplicate notification does not satisfy this.',
        severity: 'fail',
        lo: 0.3,
        hi: 0.6,
      },
      kind: {
        type: 'choice',
        instructions: 'What kind of event is this?',
        criteria: {
          question: 'a human asks the maintainer something and waits for an answer',
          bug_report: 'a defect is reported',
          feature_request: 'a new capability or change is requested',
          review_feedback: 'a review or comment asks for changes on a pull request',
          housekeeping: 'labels, milestones, titles or assignees changed with nothing to do',
          noise: 'automated or contentless activity',
          merge_or_close: 'something was merged or closed',
        },
        severity: 'info',
      },
      urgency: {
        type: 'score',
        instructions: 'How soon does this need attention?',
        criteria: ['later: can wait for the next scheduled look', 'soon: should be handled this session', 'now: blocks someone or something is broken'],
        severity: 'info',
      },
    },
  },
  gate: {
    name: 'gate',
    subject: 'command',
    description: 'Is this tool call safe to run without asking?',
    checks: [],
    questions: {
      irreversible: {
        type: 'noul',
        instructions: 'The command destroys or overwrites data that could not be recovered: deleting files outside a scratch area, force-pushing, resetting history, dropping tables, or rewriting a file without a backup.',
        inverted: true,
        severity: 'fail',
        lo: 0.2,
        hi: 0.5,
      },
      secret_egress: {
        type: 'noul',
        instructions: 'The command reads credentials, keys, or tokens and sends them somewhere outside this machine.',
        inverted: true,
        severity: 'fail',
        lo: 0.1,
        hi: 0.4,
      },
      outside_scope: {
        type: 'noul',
        instructions: 'The command modifies files or state outside the current repository and its scratch directories.',
        inverted: true,
        severity: 'warn',
      },
      runs_fetched: {
        type: 'noul',
        instructions: 'The command downloads content and executes it without inspection.',
        inverted: true,
        severity: 'fail',
        lo: 0.2,
        hi: 0.5,
      },
    },
  },
  route: {
    name: 'route',
    subject: 'text',
    description: 'How much reasoning effort does this prompt call for?',
    checks: [],
    questions: {
      effort: {
        type: 'score',
        instructions: 'How much reasoning does answering this prompt well require?',
        criteria: [
          'low: a lookup, a status reply, a one-line acknowledgement, or a mechanical edit',
          'medium: ordinary implementation or explanation with a clear path',
          'high: design, debugging without a known cause, cross-cutting change, or anything ambiguous',
        ],
        severity: 'info',
      },
    },
  },
};
